services:
  immich-kiosk:
    image: ghcr.io/enice816/immich-kiosk:clock-seconds
    container_name: immich-kiosk
    tty: true
    environment:
      LANG: "en_GB"
      TZ: "Europe/London"
    ports:
      - 3000:3000
    volumes:
      - ./config:/config
      # - ./custom.css:/custom.css
      # - ./offline-assets:/offline-assets
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
