name: Build & Publish Docker image

on:
  push:
    branches: [ "main" ]   # build when code merges to main
  release:
    types: [published]     # also build when you publish a GitHub release
  workflow_dispatch:        # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha
            type=ref,event=branch
            type=semver,pattern={{version}}   # v1.2.3
            type=semver,pattern={{major}}     # v1
            type=semver,pattern={{major}}.{{minor}}  # v1.2

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
